name: Docker Image CI/CD

on:
  workflow_dispatch:
    branches: [ master ]
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build-and-deploy:

    runs-on: ubuntu-latest

    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@master

    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: 'Login to ACR'
      uses: azure/docker-login@v1
      with:
        login-server: contappsdemo.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
      
    - name: 'Run build and deploy'
      run: |
        docker build . --file Dockerfile --tag contappsdemo.azurecr.io/nodeapi-container:$(date +%s)
        docker push contappsdemo.azurecr.io/nodeapi-container:$(date +%s)
